-- Run this once in Supabase SQL Editor.
-- Property photos use the Storage bucket configured by the app (default: property-images).

create table if not exists public.crm_leads (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  property_id bigint,
  property_title text,
  source text not null default 'website',
  stage text not null default 'new',
  notes text not null default '',
  tags jsonb not null default '[]'::jsonb,
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists crm_leads_stage_idx on public.crm_leads(stage, archived);
create index if not exists crm_leads_created_idx on public.crm_leads(created_at desc);

alter table public.crm_leads enable row level security;

-- The backend uses SUPABASE_SECRET_KEY, so server-side operations bypass RLS.
-- No public/anon policies are intentionally created for this private CRM table.
