const express = require('express');
const propertiesDb = require('../lib/properties-db');
const { SITE_URL, propertyUrl, generateSeoTitle, generateMetaDescription, generateOgTags, generateStructuredData, generateBreadcrumbs } = require('../lib/seo');
const router = express.Router();
const escape = value => String(value || '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' })[c]);

const head = ({ title, description, canonical, og = {}, noindex = false, schema }) => `<head><title>${escape(title)}</title><meta name="description" content="${escape(description)}"><link rel="canonical" href="${escape(canonical)}"><meta name="robots" content="${noindex ? 'noindex,follow' : 'index,follow,max-image-preview:large'}"><meta name="viewport" content="width=device-width,initial-scale=1">${Object.entries(og).map(([k,v]) => v ? `<meta ${k.startsWith('twitter:') ? 'name' : 'property'}="${escape(k)}" content="${escape(v)}">` : '').join('')}${schema ? `<script type="application/ld+json">${JSON.stringify(schema).replace(/</g, '\\u003c')}</script>` : ''}</head>`;
const page = (metadata, content) => `<!doctype html><html lang="en">${head(metadata)}<body><header><a href="/">WithBeasley</a><nav aria-label="Primary"><a href="/#listings">Properties</a><a href="/buying-a-home-in-san-miguel-de-allende">Buy</a><a href="/selling-a-home-in-san-miguel-de-allende">Sell</a><a href="/moving-to-san-miguel-de-allende">Relocate</a><a href="/neighborhoods">Neighborhoods</a><a href="/#contact">Contact</a></nav></header><main>${content}</main><footer><p>WithBeasley · San Miguel de Allende, Guanajuato</p><a href="/#listings">Properties</a> · <a href="/buying-a-home-in-san-miguel-de-allende">Buying guide</a> · <a href="/moving-to-san-miguel-de-allende">Relocation guide</a></footer></body></html>`;

const webPageSchema = (name, description, canonical) => ({ '@context':'https://schema.org', '@type':'WebPage', name, url:canonical, description, about:{ '@type':'Place', name:'San Miguel de Allende', address:{ '@type':'PostalAddress', addressLocality:'San Miguel de Allende', addressRegion:'Guanajuato', addressCountry:'MX' } } });
const breadcrumbSchema = items => ({ '@context':'https://schema.org', '@type':'BreadcrumbList', itemListElement:items.map((item, index) => ({ '@type':'ListItem', position:index + 1, name:item.name, item:item.url })) });
const seoSchema = (name, description, canonical, trail) => [webPageSchema(name, description, canonical), breadcrumbSchema([{ name:'Home', url:SITE_URL }, ...trail.map((name, i) => ({ name, url:i === trail.length - 1 ? canonical : SITE_URL }))])];

router.get('/properties/:slug', async (req, res, next) => {
  try {
    const p = await propertiesDb.getPropertyBySlug(req.params.slug);
    if (!p || p.archived) return res.status(404).send(page({ title:'Property Not Found | WithBeasley', description:'Browse San Miguel de Allende real estate with WithBeasley.', canonical:`${SITE_URL}/properties/${encodeURIComponent(req.params.slug)}`, noindex:true }, '<h1>Property not found</h1><p><a href="/#listings">Browse available properties</a></p>'));
    const indexable = ['for_sale', 'for_rent'].includes(p.status);
    const images = (p.images || []).filter(i => i.url).slice(0, 20).map((i,n) => `<img src="${escape(i.url)}" alt="${escape(i.alt || `${p.title} photo ${n + 1}`)}" loading="${n ? 'lazy' : 'eager'}" decoding="async">`).join('');
    const facts = [p.property_type, p.neighborhood, p.bedrooms && `${p.bedrooms} bedrooms`, p.bathrooms && `${p.bathrooms} bathrooms`].filter(Boolean).map(escape).join(' · ');
    const breadcrumbs = generateBreadcrumbs(p).map((item, index) => ({ '@type':'ListItem', position:index + 1, name:item.name, item:item.url }));
    const listingSchema = generateStructuredData(p);
    delete listingSchema['@context'];
    const schema = indexable ? {
      '@context':'https://schema.org',
      '@graph':[listingSchema, { '@type':'BreadcrumbList', itemListElement:breadcrumbs }]
    } : undefined;
    res.send(page({ title:p.seo_title || generateSeoTitle(p), description:p.meta_description || generateMetaDescription(p), canonical:propertyUrl(p.slug), og:generateOgTags(p), noindex:!indexable, schema }, `<article><nav aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/#listings">Properties</a>${p.neighborhood ? ` / <a href="/neighborhoods">${escape(p.neighborhood)}</a>` : ''} / <span aria-current="page">${escape(p.title)}</span></nav><h1>${escape(p.title)}</h1>${facts ? `<p>${facts}</p>` : ''}${p.price ? `<p>${escape(p.currency === 'MXN' ? 'MXN $' : '$')}${escape(Number(p.price).toLocaleString('en-US'))}</p>` : ''}${images ? `<section aria-label="Property photos">${images}</section>` : ''}${p.luxury_description || p.short_description ? `<section><h2>About this property</h2><p>${escape(p.luxury_description || p.short_description)}</p></section>` : ''}<section><h2>Continue your San Miguel de Allende property search</h2><p>${p.neighborhood ? `<a href="/neighborhoods">Explore San Miguel neighborhoods</a>, ` : ''}<a href="/#listings">browse available properties</a>, or <a href="/#contact">request a private consultation</a>.</p></section></article>`));
  } catch (error) { next(error); }
});

const guides = {
  '/buying-a-home-in-san-miguel-de-allende':['Buying Real Estate in San Miguel de Allende | WithBeasley','Practical guidance for buying real estate in San Miguel de Allende, from neighborhood exploration to a clear local process.','Buying real estate in San Miguel de Allende','<p>Buying a home in San Miguel de Allende is personal, especially when you are planning from another country. Start with the neighborhoods, homes, and timing that fit your goals.</p><h2>Start with a focused search</h2><p>Share your priorities and preferred areas to compare properties in context and spend time on homes worth a closer look.</p><h2>Plan the next steps</h2><p>Ask questions early and work with appropriately qualified professionals for legal, tax, and financing advice.</p>'],
  '/selling-a-home-in-san-miguel-de-allende':['Sell a Home in San Miguel de Allende | WithBeasley','Thoughtful guidance for San Miguel de Allende homeowners preparing to sell, price, market, and navigate their next move.','Selling a home in San Miguel de Allende','<p>Preparing to sell begins with a clear understanding of your home, timing, and the buyers most likely to value it.</p><h2>A considered selling plan</h2><p>Start with a conversation about your property, presentation, and goals. The right plan reflects the home itself rather than generic promises.</p>'],
  '/moving-to-san-miguel-de-allende':['Relocating to San Miguel de Allende | WithBeasley','Explore neighborhoods, homes, and practical next steps for a thoughtful relocation to San Miguel de Allende, Guanajuato.','Relocating to San Miguel de Allende','<p>Relocating is about more than choosing a house. Explore the rhythm of different neighborhoods and make a plan that suits how you want to live.</p><h2>Build a practical plan</h2><p>For residency, banking, healthcare, or similar questions, consult the relevant qualified professionals. WithBeasley can help you begin with the property-search side of your move.</p>'],
  '/neighborhoods':['San Miguel de Allende Neighborhood Guide | WithBeasley','Explore San Miguel de Allende neighborhoods and begin a more focused search for a home that fits your lifestyle.','Explore San Miguel de Allende neighborhoods','<p>Every neighborhood has its own character. Exploring in person is the best way to understand the setting, pace, and homes that feel right to you.</p><p><a href="/#listings">Browse available properties</a> or <a href="/#contact">talk with WithBeasley about your search</a>.</p>'],
  '/homes-for-sale-san-miguel-de-allende':['Homes for Sale in San Miguel de Allende | WithBeasley','Explore homes for sale in San Miguel de Allende by neighborhood, lifestyle, property type, and budget.','Homes for sale in San Miguel de Allende','<p>Searching for homes for sale in San Miguel de Allende is easier when you begin with how you want to live. Some buyers prioritize walkability to Centro, while others want gardens, privacy, views, newer construction, or more space outside the historic core.</p><h2>Choose the right starting point</h2><p>Start with a realistic budget, preferred property type, desired number of bedrooms, and the neighborhoods you would consider. If you are new to San Miguel, compare several areas before narrowing your search.</p><h2>Compare homes beyond the photos</h2><p>When reviewing a property, consider location, access, condition, outdoor space, maintenance needs, and how the home fits your plans. Ask appropriately qualified professionals for legal, tax, title, or financing advice.</p><h2>Explore the local market</h2><p>Use the live property collection to review current opportunities, then explore the <a href="/neighborhoods">San Miguel de Allende neighborhood guide</a> or read about <a href="/buying-a-home-in-san-miguel-de-allende">buying property in San Miguel de Allende</a>.</p><p><a href="/#listings">View current homes for sale</a> or <a href="/#contact">request a focused property search</a>.</p>'],
  '/homes-for-rent-san-miguel-de-allende':['Homes for Rent in San Miguel de Allende | WithBeasley','Explore homes for rent in San Miguel de Allende by neighborhood, budget, timing, and lifestyle needs.','Homes for rent in San Miguel de Allende','<p>Renting in San Miguel de Allende can be a practical way to settle into the city, explore neighborhoods, or plan a longer stay. Availability and terms vary, so begin with your move date, approximate budget, preferred areas, and whether you need a furnished home.</p><h2>Decide what matters most</h2><p>Consider walkability, parking, outdoor space, pets, number of bedrooms, internet needs, and access to the places you use regularly. A home that looks right online may feel very different depending on its location and daily surroundings.</p><h2>Plan your rental search</h2><p>Share your timing and requirements early. Review current options, compare neighborhoods, and confirm the details of any property directly before making commitments.</p><h2>Explore before you decide</h2><p>Visit the <a href="/neighborhoods">neighborhood guide</a> to compare areas or read the <a href="/moving-to-san-miguel-de-allende">moving to San Miguel de Allende guide</a> if you are planning a relocation.</p><p><a href="/#listings">View current rental opportunities</a> or <a href="/#contact">tell us what you need</a>.</p>'],
  '/luxury-real-estate-san-miguel-de-allende':['Luxury Real Estate in San Miguel de Allende | WithBeasley','Explore distinctive luxury homes and real estate opportunities in San Miguel de Allende, Guanajuato.','Luxury real estate in San Miguel de Allende','<p>San Miguel de Allende offers a wide range of distinctive homes, from historic properties to contemporary residences. A thoughtful search starts with the setting, architecture, outdoor spaces, privacy, and lifestyle you want.</p><h2>Explore distinctive properties</h2><p>Browse current listings and compare homes based on the details that matter most to you.</p><p><a href="/#listings">Explore properties</a> or <a href="/#contact">start a private search</a>.</p>'],
  '/moving-to-san-miguel-de-allende':['Moving to San Miguel de Allende | WithBeasley','A practical starting point for moving to San Miguel de Allende, with neighborhood and real estate guidance for your next chapter.','Moving to San Miguel de Allende','<p>Moving to San Miguel de Allende starts with understanding how you want to live. Explore neighborhoods, rental options, homes for sale, and the practical questions you need answered before making a move.</p><h2>Start with the neighborhood</h2><p>Think about walkability, daily routines, space, budget, and the type of home that fits your plans. Then narrow the property search.</p><h2>Get the right professional advice</h2><p>For immigration, tax, legal, healthcare, or financial questions, use the appropriate qualified professionals. For the real estate side, start with a focused property search.</p><p><a href="/moving-to-san-miguel-de-allende">Read the relocation guide</a> or <a href="/#contact">contact WithBeasley</a>.</p>']
};

const neighborhoodPages = {
  '/neighborhoods/guadalupe':['Guadalupe San Miguel de Allende Real Estate | WithBeasley','Explore homes and real estate in Guadalupe, San Miguel de Allende, and compare available properties with a focused local search.','Guadalupe real estate in San Miguel de Allende'],
  '/neighborhoods/la-lejona':['La Lejona San Miguel de Allende Real Estate | WithBeasley','Explore homes and real estate in La Lejona, San Miguel de Allende, and review current property opportunities.','La Lejona real estate in San Miguel de Allende'],
  '/neighborhoods/los-senderos':['Los Senderos San Miguel de Allende Real Estate | WithBeasley','Explore homes and real estate in Los Senderos, San Miguel de Allende, and find properties that match your plans.','Los Senderos real estate in San Miguel de Allende'],
  '/neighborhoods/malanquin':['Malanquín San Miguel de Allende Real Estate | WithBeasley','Explore homes and real estate in Malanquín, San Miguel de Allende, with current property search support.','Malanquín real estate in San Miguel de Allende'],
  '/neighborhoods/ojo-de-agua':['Ojo de Agua San Miguel de Allende Real Estate | WithBeasley','Explore homes and real estate in Ojo de Agua, San Miguel de Allende, and narrow your search by property needs.','Ojo de Agua real estate in San Miguel de Allende'],
  '/neighborhoods/zirandaro':['Zirándaro San Miguel de Allende Real Estate | WithBeasley','Explore homes and real estate in Zirándaro, San Miguel de Allende, and compare current property opportunities.','Zirándaro real estate in San Miguel de Allende']
};

Object.entries(guides).forEach(([path, [title, description, heading, body]]) => router.get(path, (req,res) => {
  const canonical = SITE_URL + path;
  res.send(page({ title, description, canonical, og:{ 'og:title':title, 'og:description':description, 'og:type':'website', 'og:url':canonical, 'og:site_name':'WithBeasley', 'og:locale':'en_US', 'twitter:card':'summary', 'twitter:title':title, 'twitter:description':description }, schema:seoSchema(heading, description, canonical, [heading]) }, `<article><h1>${heading}</h1>${body}<p><a href="/#contact">Start a private consultation</a></p></article>`));
}));

Object.entries(neighborhoodPages).forEach(([path, [title, description, heading]]) => router.get(path, (req,res) => {
  const canonical = SITE_URL + path;
  const name = path.split('/').pop().replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  const body = `<p>Explore ${escape(name)} homes and real estate in San Miguel de Allende. This page is a starting point for comparing current properties and deciding what matters most in your search.</p><h2>Search by property and lifestyle</h2><p>Consider the home type, budget, space, timing, and location that fit your plans. Then compare available properties rather than relying on a generic neighborhood description.</p><h2>See current opportunities</h2><p><a href="/#listings">Browse available properties</a> or <a href="/#contact">request a focused ${escape(name)} search</a>.</p>`;
  res.send(page({ title, description, canonical, og:{ 'og:title':title, 'og:description':description, 'og:type':'website', 'og:url':canonical, 'og:site_name':'WithBeasley', 'og:locale':'en_US', 'twitter:card':'summary', 'twitter:title':title, 'twitter:description':description }, schema:seoSchema(heading, description, canonical, ['Neighborhoods', heading]) }, `<article><h1>${heading}</h1>${body}</article>`));
}));

module.exports = router;
