const express = require('express');
const propertiesDb = require('../lib/properties-db');
const { SITE_URL, propertyUrl, generateSeoTitle, generateMetaDescription, generateOgTags, generateStructuredData } = require('../lib/seo');
const router = express.Router();
const escape = value => String(value || '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' })[c]);
const head = ({ title, description, canonical, og = {}, noindex = false, schema }) => `<head><title>${escape(title)}</title><meta name="description" content="${escape(description)}"><link rel="canonical" href="${escape(canonical)}"><meta name="robots" content="${noindex ? 'noindex,follow' : 'index,follow,max-image-preview:large'}"><meta name="viewport" content="width=device-width,initial-scale=1">${Object.entries(og).map(([k,v]) => v ? `<meta ${k.startsWith('twitter:') ? 'name' : 'property'}="${escape(k)}" content="${escape(v)}">` : '').join('')}${schema ? `<script type="application/ld+json">${JSON.stringify(schema).replace(/</g, '\\u003c')}</script>` : ''}</head>`;
const page = (metadata, content) => `<!doctype html><html lang="en">${head(metadata)}<body><header><a href="/">Blaze Beasley</a><nav aria-label="Primary"><a href="/#listings">Properties</a><a href="/buying-san-miguel-de-allende">Buy</a><a href="/selling-san-miguel-de-allende">Sell</a><a href="/neighborhoods">Neighborhoods</a><a href="/#contact">Contact</a></nav></header><main>${content}</main><footer><p>Blaze Beasley · San Miguel de Allende, Guanajuato</p><a href="/#listings">Properties</a> · <a href="/buying-san-miguel-de-allende">Buying guide</a> · <a href="/relocating-to-san-miguel-de-allende">Relocation guide</a></footer></body></html>`;
router.get('/properties/:slug', async (req, res, next) => {
  try {
    const p = await propertiesDb.getPropertyBySlug(req.params.slug);
    if (!p || p.archived) return res.status(404).send(page({ title:'Property Not Found | Blaze Beasley', description:'Browse San Miguel de Allende real estate with Blaze Beasley.', canonical:`${SITE_URL}/properties/${encodeURIComponent(req.params.slug)}`, noindex:true }, '<h1>Property not found</h1><p><a href="/#listings">Browse available properties</a></p>'));
    const indexable = ['for_sale', 'for_rent'].includes(p.status);
    const images = (p.images || []).filter(i => i.url).slice(0, 20).map((i,n) => `<img src="${escape(i.url)}" alt="${escape(i.alt || `${p.title} photo ${n + 1}`)}" loading="${n ? 'lazy' : 'eager'}">`).join('');
    const facts = [p.property_type, p.neighborhood, p.bedrooms && `${p.bedrooms} bedrooms`, p.bathrooms && `${p.bathrooms} bathrooms`].filter(Boolean).map(escape).join(' · ');
    res.send(page({ title:p.seo_title || generateSeoTitle(p), description:p.meta_description || generateMetaDescription(p), canonical:propertyUrl(p.slug), og:generateOgTags(p), noindex:!indexable, schema:indexable ? generateStructuredData(p) : undefined }, `<article><p><a href="/#listings">Properties</a>${p.neighborhood ? ` / <a href="/neighborhoods">${escape(p.neighborhood)}</a>` : ''}</p><h1>${escape(p.title)}</h1>${facts ? `<p>${facts}</p>` : ''}${p.price ? `<p>${escape(p.currency === 'MXN' ? 'MXN $' : '$')}${escape(Number(p.price).toLocaleString('en-US'))}</p>` : ''}${images ? `<section aria-label="Property photos">${images}</section>` : ''}${p.luxury_description || p.short_description ? `<section><h2>About this property</h2><p>${escape(p.luxury_description || p.short_description)}</p></section>` : ''}<section><h2>Explore San Miguel de Allende real estate</h2><p><a href="/#contact">Request a private consultation</a> or <a href="/#listings">browse available properties</a>.</p></section></article>`));
  } catch (error) { next(error); }
});
const guides = {
  '/buying-san-miguel-de-allende':['Buying Real Estate in San Miguel de Allende | Blaze Beasley','Practical guidance for buying real estate in San Miguel de Allende, from neighborhood exploration to a clear local process.','Buying real estate in San Miguel de Allende','<p>Buying a home in San Miguel de Allende is personal, especially when you are planning from another country. Start with the neighborhoods, homes, and timing that fit your goals.</p><h2>Start with a focused search</h2><p>Share your priorities and preferred areas to compare properties in context and spend time on homes worth a closer look.</p><h2>Plan the next steps</h2><p>Ask questions early and work with appropriately qualified professionals for legal, tax, and financing advice.</p>'],
  '/selling-san-miguel-de-allende':['Sell a Home in San Miguel de Allende | Blaze Beasley','Thoughtful representation for San Miguel de Allende homeowners preparing to sell, price, market, and navigate their next move.','Selling a home in San Miguel de Allende','<p>Preparing to sell begins with a clear understanding of your home, timing, and the buyers most likely to value it.</p><h2>A considered selling plan</h2><p>Start with a conversation about your property, presentation, and goals. The right plan reflects the home itself rather than generic promises.</p>'],
  '/relocating-to-san-miguel-de-allende':['Relocating to San Miguel de Allende | Blaze Beasley','Explore neighborhoods, homes, and practical next steps for a thoughtful relocation to San Miguel de Allende, Guanajuato.','Relocating to San Miguel de Allende','<p>Relocating is about more than choosing a house. Explore the rhythm of different neighborhoods and make a plan that suits how you want to live.</p><h2>Build a practical plan</h2><p>For residency, banking, healthcare, or similar questions, consult the relevant qualified professionals. Blaze can help you begin with the real estate side of your move.</p>'],
  '/neighborhoods':['San Miguel de Allende Neighborhood Guide | Blaze Beasley','Explore San Miguel de Allende neighborhoods and begin a more focused search for a home that fits your lifestyle.','Explore San Miguel de Allende neighborhoods','<p>Every neighborhood has its own character. Exploring in person is the best way to understand the setting, pace, and homes that feel right to you.</p><p><a href="/#listings">Browse available properties</a> or <a href="/#contact">talk with Blaze about your search</a>.</p>'],
};
Object.entries(guides).forEach(([path, [title, description, heading, body]]) => router.get(path, (req,res) => { const canonical = SITE_URL + path; res.send(page({ title, description, canonical, og:{ 'og:title':title, 'og:description':description, 'og:type':'website', 'og:url':canonical, 'og:site_name':'Blaze Beasley Real Estate', 'twitter:card':'summary', 'twitter:title':title, 'twitter:description':description }, schema:{ '@context':'https://schema.org', '@type':'WebPage', name:heading, url:canonical, description } }, `<article><h1>${heading}</h1>${body}<p><a href="/#contact">Start a private consultation</a></p></article>`)); }));
module.exports = router;
